/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Alone in the Dark: The New Nightmare)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800237E0u
#define func_800237E0 BootEntry  /* alias */
